import json
import os

notebook_path = 'notebooks/gru_random_forest_improved.ipynb'

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# --- Step 1: Update Imports (Cell 1) ---
nb['cells'][1]['source'] = [
    "import os\n",
    "import re\n",
    "import zipfile\n",
    "import urllib.request\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import classification_report, accuracy_score, confusion_matrix\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing.text import Tokenizer\n",
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import (\n",
    "    Embedding, GRU, Dense, Dropout, SpatialDropout1D, Bidirectional,\n",
    "    Input, Concatenate, GlobalAveragePooling1D, GlobalMaxPooling1D\n",
    ")\n",
    "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau\n",
    "\n",
    "# --- Added for Random Forest Lexicon Features ---\n",
    "import nltk\n",
    "from nltk.sentiment.vader import SentimentIntensityAnalyzer\n",
    "try:\n",
    "    nltk.data.find('sentiment/vader_lexicon.zip')\n",
    "except LookupError:\n",
    "    nltk.download('vader_lexicon')\n",
    "\n",
    "# Fix random seeds so results are reproducible each run\n",
    "np.random.seed(42)\n",
    "tf.random.set_seed(42)\n",
    "\n",
    "# Download GloVe 100d vectors from Stanford\n",
    "glove_url = \"https://nlp.stanford.edu/data/glove.6B.zip\"\n",
    "glove_zip = \"glove.6B.zip\"\n",
    "glove_local_path = 'glove.6B.100d.txt'\n",
    "glove_kaggle_path = '/kaggle/input/glove6b100dtxt/glove.6B.100d.txt'\n",
    "\n",
    "if os.path.exists(glove_kaggle_path):\n",
    "    print(\"Using Kaggle GloVe path.\")\n",
    "    glove_path = glove_kaggle_path\n",
    "elif not os.path.exists(glove_local_path):\n",
    "    print(\"Downloading GloVe vectors...\")\n",
    "    opener = urllib.request.build_opener()\n",
    "    opener.addheaders = [('User-agent', 'Mozilla/5.0')]\n",
    "    urllib.request.install_opener(opener)\n",
    "    urllib.request.urlretrieve(glove_url, glove_zip)\n",
    "    with zipfile.ZipFile(glove_zip, 'r') as z:\n",
    "        z.extract(glove_local_path)\n",
    "    glove_path = glove_local_path\n",
    "else:\n",
    "    glove_path = glove_local_path\n",
    "\n",
    "# Load GloVe vectors into memory dictionary\n",
    "print(\"Loading GloVe vectors into memory...\")\n",
    "embeddings_lookup = {}\n",
    "with open(glove_path, 'r', encoding='utf-8') as f:\n",
    "    for line in f:\n",
    "        values = line.split()\n",
    "        word = values[0]\n",
    "        coefs = np.asarray(values[1:], dtype='float32')\n",
    "        embeddings_lookup[word] = coefs\n",
    "print(f\"Loaded {len(embeddings_lookup):,} word vectors.\")\n"
]

# --- Step 7: Preparing Sequence and Metadata for GRU (Cell 15) ---
nb['cells'][15]['source'] = [
    "VOCAB_SIZE = 15000\n",
    "MAX_LEN    = 150   # Increased to 150 to capture complete email context\n",
    "\n",
    "# Fit tokenizer on training text only\n",
    "tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token=\"<UNK>\")\n",
    "tokenizer.fit_on_texts(train_df['cleaned_text'])\n",
    "\n",
    "def tokenize_and_pad(texts):\n",
    "    seqs = tokenizer.texts_to_sequences(texts)\n",
    "    return pad_sequences(seqs, maxlen=MAX_LEN, padding='post', truncating='post')\n",
    "\n",
    "X_train_gru = tokenize_and_pad(train_df['cleaned_text'])\n",
    "X_val_gru   = tokenize_and_pad(val_df['cleaned_text'])\n",
    "X_test_gru  = tokenize_and_pad(test_df['cleaned_text'])\n",
    "\n",
    "y_train_gru = train_df['label'].values\n",
    "y_val_gru   = val_df['label'].values\n",
    "y_test_gru  = test_df['label'].values\n",
    "\n",
    "# --- Metadata columns requested by the user ---\n",
    "meta_cols = ['exclamation_count', 'is_all_caps', 'char_cnt', 'word_cnt', \n",
    "             'has_platform_mention', 'has_service_alert']\n",
    "\n",
    "# --- Scale Structural Metadata Features for GRU branch ---\n",
    "scaler = StandardScaler()\n",
    "X_train_meta = scaler.fit_transform(train_df[meta_cols].values)\n",
    "X_val_meta   = scaler.transform(val_df[meta_cols].values)\n",
    "X_test_meta  = scaler.transform(test_df[meta_cols].values)\n",
    "\n",
    "# Build the GloVe embedding matrix\n",
    "embedding_matrix = np.zeros((VOCAB_SIZE, 100))\n",
    "matched = 0\n",
    "for word, idx in tokenizer.word_index.items():\n",
    "    if idx < VOCAB_SIZE:\n",
    "        vec = embeddings_lookup.get(word)\n",
    "        if vec is not None:\n",
    "            embedding_matrix[idx] = vec\n",
    "            matched += 1\n",
    "\n",
    "print(f\"GloVe coverage: {matched:,} / {VOCAB_SIZE:,} tokens matched\")\n"
]

# --- Step 7: Multi-Input GRU Model Build (Cell 16) ---
nb['cells'][16]['source'] = [
    "# --- Build the Multi-Input GRU Model using Keras Functional API ---\n",
    "\n",
    "# Branch A: The Text Sequence Path\n",
    "text_input = Input(shape=(MAX_LEN,), name='text_input')\n",
    "x = Embedding(\n",
    "    input_dim=VOCAB_SIZE,\n",
    "    output_dim=100,\n",
    "    weights=[embedding_matrix],\n",
    "    input_length=MAX_LEN,\n",
    "    trainable=True\n",
    ")(text_input)\n",
    "x = SpatialDropout1D(0.3)(x)\n",
    "\n",
    "# Bidirectional GRU layer\n",
    "x = Bidirectional(GRU(64, return_sequences=True))(x)\n",
    "\n",
    "# Dual Pooling: captues peak sentiment (Max) and overall context (Average)\n",
    "avg_pool = GlobalAveragePooling1D()(x)\n",
    "max_pool = GlobalMaxPooling1D()(x)\n",
    "conc_text = Concatenate()([avg_pool, max_pool])\n",
    "\n",
    "# Branch B: The Scaled Metadata Path (fixes the Neutral Trap)\n",
    "meta_input = Input(shape=(len(meta_cols),), name='meta_input')\n",
    "\n",
    "# Merge both branches\n",
    "conc_all = Concatenate()([conc_text, meta_input])\n",
    "\n",
    "# Classification head\n",
    "d = Dense(128, activation='relu')(conc_all)\n",
    "d = Dropout(0.4)(d)\n",
    "d = Dense(64, activation='relu')(d)\n",
    "d = Dropout(0.3)(d)\n",
    "outputs = Dense(3, activation='softmax')(d)\n",
    "\n",
    "gru_model = Model(inputs=[text_input, meta_input], outputs=outputs)\n",
    "\n",
    "# Compile using clipnorm=1.0 for stability\n",
    "gru_model.compile(\n",
    "    loss='sparse_categorical_crossentropy',\n",
    "    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3, clipnorm=1.0),\n",
    "    metrics=['accuracy']\n",
    ")\n",
    "\n",
    "gru_model.summary()\n"
]

# --- Step 7: Training the GRU Model (Cell 17) ---
nb['cells'][17]['source'] = [
    "# --- Compute class weights ---\n",
    "classes = np.unique(y_train_gru)\n",
    "class_weights_arr = compute_class_weight(class_weight='balanced', classes=classes, y=y_train_gru)\n",
    "class_weights = dict(zip(classes, class_weights_arr))\n",
    "\n",
    "# --- Callbacks ---\n",
    "early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n",
    "reduce_lr  = ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=1, min_lr=1e-6)\n",
    "\n",
    "# --- Train with Dual Inputs ---\n",
    "print(\"Training Multi-Input GRU...\")\n",
    "history = gru_model.fit(\n",
    "    [X_train_gru, X_train_meta], y_train_gru,\n",
    "    epochs=12,\n",
    "    batch_size=64,\n",
    "    validation_data=([X_val_gru, X_val_meta], y_val_gru),\n",
    "    class_weight=class_weights,\n",
    "    callbacks=[early_stop, reduce_lr],\n",
    "    verbose=1\n",
    ")\n"
]

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)
