import json
import os

notebook_path = 'notebooks/IVY_SVM_BiLSTM.ipynb'

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# --- Step 1: Update Imports (Cell 2) ---
nb['cells'][2]['source'] = [
    "import os\n",
    "import re\n",
    "import string\n",
    "import zipfile\n",
    "import urllib.request\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing.text import Tokenizer\n",
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import (\n",
    "    Embedding, LSTM, Bidirectional, Dense, Dropout, SpatialDropout1D,\n",
    "    Input, Concatenate, GlobalAveragePooling1D, GlobalMaxPooling1D\n",
    ")\n",
    "\n",
    "# --- Added for SVM Lexicon Features ---\n",
    "import nltk\n",
    "from nltk.sentiment.vader import SentimentIntensityAnalyzer\n",
    "try:\n",
    "    nltk.data.find('sentiment/vader_lexicon.zip')\n",
    "except LookupError:\n",
    "    nltk.download('vader_lexicon')\n",
    "\n",
    "# Fix random seeds so results are reproducible each run\n",
    "np.random.seed(42)\n",
    "tf.random.set_seed(42)\n",
    "\n",
    "# GloVe paths - check Kaggle input first to avoid download errors\n",
    "glove_kaggle_path = '/kaggle/input/glove6b100dtxt/glove.6B.100d.txt'\n",
    "glove_local_path = 'glove.6B.100d.txt'\n",
    "glove_url = \"https://nlp.stanford.edu/data/glove.6B.zip\"\n",
    "glove_zip = \"glove.6B.zip\"\n",
    "\n",
    "if os.path.exists(glove_kaggle_path):\n",
    "    print(\"Using Kaggle's GloVe dataset.\")\n",
    "    glove_path = glove_kaggle_path\n",
    "elif not os.path.exists(glove_local_path):\n",
    "    print(\"Downloading GloVe vectors from Stanford (this takes a few minutes)...\")\n",
    "    try:\n",
    "        opener = urllib.request.build_opener()\n",
    "        opener.addheaders = [('User-agent', 'Mozilla/5.0')]\n",
    "        urllib.request.install_opener(opener)\n",
    "        urllib.request.urlretrieve(glove_url, glove_zip)\n",
    "        print(\"Download done. Extracting...\")\n",
    "        with zipfile.ZipFile(glove_zip, 'r') as z:\n",
    "            z.extract(glove_local_path)\n",
    "        print(\"GloVe vectors ready.\")\n",
    "        glove_path = glove_local_path\n",
    "    except Exception as e:\n",
    "        print(f\"Download failed: {e}\")\n",
    "        print(\"PLEASE ENABLE INTERNET IN KAGGLE SETTINGS OR ADD GLOVE DATASET.\")\n",
    "        glove_path = None\n",
    "else:\n",
    "    print(\"GloVe vectors already available locally.\")\n",
    "    glove_path = glove_local_path\n",
    "\n",
    "# Load GloVe vectors into a memory dictionary\n",
    "if glove_path:\n",
    "    print(\"Loading GloVe vectors into memory...\")\n",
    "    embeddings_lookup = {}\n",
    "    with open(glove_path, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            values = line.split()\n",
    "            word = values[0]\n",
    "            coefs = np.asarray(values[1:], dtype='float32')\n",
    "            embeddings_lookup[word] = coefs\n",
    "    print(f\"Loaded {len(embeddings_lookup):,} word vectors.\")"
]

# --- Step 4: Surgical Cleaning & Feature Extraction (Cell 9) ---
nb['cells'][9]['source'] = [
    "# --- Slang mapping including WhatsApp shortcuts ---\n",
    "slang_dictionary = {\n",
    "    r'\\bu\\b': 'you', r'\\bpls\\b': 'please', r'\\bplz\\b': 'please',\n",
    "    r'\\btmrw\\b': 'tomorrow', r'\\bwat\\b': 'what', r'\\bwud\\b': 'would',\n",
    "    r'\\bcuz\\b': 'because', r'\\bbtw\\b': 'by the way', r'\\bidk\\b': 'i do not know',\n",
    "    r'\\bomg\\b': 'oh my god', r'\\blol\\b': 'laughing', r'\\bthx\\b': 'thanks',\n",
    "    r'\\bsry\\b': 'sorry', r'\\bwanna\\b': 'want to', r'\\bgonna\\b': 'going to',\n",
    "    r'\\bur\\b': 'your', r'\\br\\b': 'are', r'\\bn\\b': 'and', r'\\bok\\b': 'okay'\n",
    "}\n",
    "\n",
    "def extract_meta_features(df):\n",
    "    \"\"\"\n",
    "    Extracts structural metadata indicators before cleaning strips punctuation/casing.\n",
    "    \"\"\"\n",
    "    # 1. Count of exclamations and question marks\n",
    "    df['exclamation_count'] = df['text'].apply(lambda x: str(x).count('!'))\n",
    "    df['question_count'] = df['text'].apply(lambda x: str(x).count('?'))\n",
    "    \n",
    "    # 2. Check for HTML fragments\n",
    "    df['has_html_artifacts'] = df['text'].apply(lambda x: 1 if re.search(r'<.*?>', str(x)) else 0)\n",
    "    \n",
    "    # 3. Check for shout capitalization (ALL CAPS)\n",
    "    df['is_all_caps'] = df['text'].apply(lambda x: 1 if str(x).isupper() and len(str(x)) > 5 else 0)\n",
    "    \n",
    "    # 4. Characters and words length\n",
    "    df['char_cnt'] = df['text'].apply(lambda x: len(str(x)))\n",
    "    df['word_cnt'] = df['text'].apply(lambda x: len(str(x).split()))\n",
    "    \n",
    "    # 5. Domain Shift Indicators (Technical platform names and billing alerts)\n",
    "    df['has_platform_mention'] = df['text'].apply(\n",
    "        lambda x: 1 if re.search(r'\\b(github|slack|coursera|udemy|paystack|railway|netlify|heroku)\\b', str(x).lower()) else 0\n",
    "    )\n",
    "    df['has_service_alert'] = df['text'].apply(\n",
    "        lambda x: 1 if re.search(r'\\b(invoice|billing|terminate|security|alert|reminder)\\b', str(x).lower()) else 0\n",
    "    )\n",
    "    return df\n",
    "\n",
    "def surgical_cleaner(text):\n",
    "    if type(text) != str: return \"\"\n",
    "    text = text.lower()\n",
    "    \n",
    "    # Remove HTML tags & URLs\n",
    "    text = re.sub(r'http\\S+|www\\.\\S+|@\\w+', '', text)\n",
    "    text = re.sub(r'<.*?>', '', text)\n",
    "    \n",
    "    # Strip common automated signatures\n",
    "    text = re.sub(r'sent from my (iphone|android|mobile)', '', text)\n",
    "    text = re.sub(r'please consider the environment before printing', '', text)\n",
    "    text = re.sub(r'--- forwarded message ---', '', text)\n",
    "    \n",
    "    # Standardize slang\n",
    "    for slang, correct in slang_dictionary.items():\n",
    "        text = re.sub(slang, correct, text)\n",
    "        \n",
    "    # Standardize contractions\n",
    "    text = re.sub(r\"can't\", \"cannot\", text)\n",
    "    text = re.sub(r\"don't\", \"do not\", text)\n",
    "    text = re.sub(r\"isn't\", \"is not\", text)\n",
    "    \n",
    "    # Strip punctuation\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    text = re.sub(r'\\s+', ' ', text).strip()\n",
    "    \n",
    "    return text if text else \"notification\"\n",
    "\n",
    "# --- Process Datasets ---\n",
    "print(\"Extracting structural metadata indicators...\")\n",
    "train_df = extract_meta_features(train_df)\n",
    "val_df   = extract_meta_features(val_df)\n",
    "test_df  = extract_meta_features(test_df)\n",
    "\n",
    "print(\"Applying surgical cleaner...\")\n",
    "train_df['clean'] = train_df['text'].apply(surgical_cleaner)\n",
    "val_df['clean']   = val_df['text'].apply(surgical_cleaner)\n",
    "test_df['clean']  = test_df['text'].apply(surgical_cleaner)\n",
    "\n",
    "print(\"Surgical cleaning complete!\")\n"
]

# --- Step 5: Preparing Features for SVM (Cell 13) ---
nb['cells'][13]['source'] = [
    "# --- TF-IDF Weighted GloVe Vector Pooling ---\n",
    "def compute_tfidf_weighted_glove(texts, tfidf_vec, glove_dict, dim=100):\n",
    "    tfidf_matrix = tfidf_vec.transform(texts).toarray()\n",
    "    feature_names = tfidf_vec.get_feature_names_out()\n",
    "    word2idx = {word: idx for idx, word in enumerate(feature_names)}\n",
    "    \n",
    "    vecs = []\n",
    "    for i, text in enumerate(texts):\n",
    "        tokens = text.split()\n",
    "        token_vecs = []\n",
    "        weights = []\n",
    "        for w in tokens:\n",
    "            if w in glove_dict:\n",
    "                token_vecs.append(glove_dict[w])\n",
    "                if w in word2idx:\n",
    "                    weights.append(tfidf_matrix[i, word2idx[w]])\n",
    "                else:\n",
    "                    weights.append(1e-3)\n",
    "        if token_vecs:\n",
    "            token_vecs = np.array(token_vecs)\n",
    "            weights = np.array(weights)\n",
    "            weight_sum = np.sum(weights)\n",
    "            if weight_sum > 0:\n",
    "                weights = weights / weight_sum\n",
    "                weighted_vec = np.sum(token_vecs * weights[:, np.newaxis], axis=0)\n",
    "            else:\n",
    "                weighted_vec = np.mean(token_vecs, axis=0)\n",
    "            vecs.append(weighted_vec)\n",
    "        else:\n",
    "            vecs.append(np.zeros(dim))\n",
    "    return np.array(vecs)\n",
    "\n",
    "# --- VADER Sentiment Feature Extraction ---\n",
    "print(\"Extracting VADER lexicon scores...\")\n",
    "sia = SentimentIntensityAnalyzer()\n",
    "def extract_vader_features(texts):\n",
    "    vader_feats = []\n",
    "    for text in texts:\n",
    "        scores = sia.polarity_scores(str(text))\n",
    "        vader_feats.append([scores['neg'], scores['neu'], scores['pos'], scores['compound']])\n",
    "    return np.array(vader_feats)\n",
    "\n",
    "vader_train = extract_vader_features(train_df['text'])\n",
    "vader_val   = extract_vader_features(val_df['text'])\n",
    "vader_test  = extract_vader_features(test_df['text'])\n",
    "\n",
    "# --- Set up TF-IDF for weight computing ---\n",
    "tfidf_svm = TfidfVectorizer(max_features=500, ngram_range=(1,2), sublinear_tf=True, min_df=2)\n",
    "tfidf_svm.fit(train_df['clean'])\n",
    "\n",
    "X_train_glove = compute_tfidf_weighted_glove(train_df['clean'], tfidf_svm, embeddings_lookup)\n",
    "X_val_glove   = compute_tfidf_weighted_glove(val_df['clean'],   tfidf_svm, embeddings_lookup)\n",
    "X_test_glove  = compute_tfidf_weighted_glove(test_df['clean'],  tfidf_svm, embeddings_lookup)\n",
    "\n",
    "# --- Standardize Metadata features to avoid length bias ---\n",
    "meta_cols = ['exclamation_count', 'question_count', 'has_html_artifacts',\n",
    "             'is_all_caps', 'char_cnt', 'word_cnt',\n",
    "             'has_platform_mention', 'has_service_alert']\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_meta = scaler.fit_transform(train_df[meta_cols].values)\n",
    "X_val_meta   = scaler.transform(val_df[meta_cols].values)\n",
    "X_test_meta  = scaler.transform(test_df[meta_cols].values)\n",
    "\n",
    "# --- Stack everything together ---\n",
    "X_train_svm = np.hstack([X_train_glove, vader_train, X_train_meta])\n",
    "X_val_svm   = np.hstack([X_val_glove,   vader_val,   X_val_meta])\n",
    "X_test_svm  = np.hstack([X_test_glove,  vader_test,  X_test_meta])\n",
    "\n",
    "print(f\"SVM feature matrix shape — Train: {X_train_svm.shape}, Test: {X_test_svm.shape}\")\n"
]

# --- Step 5.1 & 6: SVM Training and Tuning (Cell 16 & 18) ---
nb['cells'][16]['source'] = [
    "best_c = 1.0\n",
    "best_f1 = 0\n",
    "\n",
    "# Grid search C using balanced class weight weights\n",
    "for c_val in [0.1, 1.0, 5.0, 10.0]:\n",
    "    temp_svm = SVC(kernel='rbf', C=c_val, class_weight='balanced', random_state=42)\n",
    "    temp_svm.fit(X_train_svm, y_train)\n",
    "    temp_preds = temp_svm.predict(X_val_svm)\n",
    "    current_f1 = f1_score(y_val, temp_preds, average='macro')\n",
    "    \n",
    "    print(f\"Testing RBF SVM with C={c_val}, Validation F1: {current_f1:.4f}\")\n",
    "    \n",
    "    if current_f1 > best_f1:\n",
    "        best_f1 = current_f1\n",
    "        best_c = c_val\n",
    "\n",
    "print(f\"\\nSuccess! The best C value is {best_c} with validation F1-score of {best_f1:.4f}\")\n"
]

nb['cells'][18]['source'] = [
    "# Train and evaluate final optimized SVM\n",
    "svm_model = SVC(kernel='rbf', C=best_c, class_weight='balanced', random_state=42)\n",
    "svm_model.fit(X_train_svm, y_train)\n",
    "\n",
    "svm_val_preds = svm_model.predict(X_val_svm)\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\"  OPTIMIZED SVM — Validation Report\")\n",
    "print(\"=\"*50)\n",
    "print(classification_report(y_val, svm_val_preds, target_names=label_mapping.keys()))\n"
]

# --- Step 7: Preparing Sequence & GloVe Matrix for Bi-LSTM (Cell 20) ---
nb['cells'][20]['source'] = [
    "MAX_NB_WORDS = 20000\n",
    "MAX_LEN = 150  # increased from 100 to capture complete email context\n",
    "\n",
    "tokenizer = Tokenizer(num_words=MAX_NB_WORDS, oov_token='<OOV>')\n",
    "tokenizer.fit_on_texts(train_df['clean'])\n",
    "\n",
    "X_train_seq = pad_sequences(tokenizer.texts_to_sequences(train_df['clean']), maxlen=MAX_LEN, padding='post', truncating='post')\n",
    "X_val_seq   = pad_sequences(tokenizer.texts_to_sequences(val_df['clean']),   maxlen=MAX_LEN, padding='post', truncating='post')\n",
    "X_test_seq  = pad_sequences(tokenizer.texts_to_sequences(test_df['clean']),  maxlen=MAX_LEN, padding='post', truncating='post')\n",
    "\n",
    "# Build GloVe embedding matrix\n",
    "embedding_matrix = np.zeros((MAX_NB_WORDS, 100))\n",
    "matched = 0\n",
    "for word, idx in tokenizer.word_index.items():\n",
    "    if idx < MAX_NB_WORDS:\n",
    "        vec = embeddings_lookup.get(word)\n",
    "        if vec is not None:\n",
    "            embedding_matrix[idx] = vec\n",
    "            matched += 1\n",
    "\n",
    "print(f\"GloVe Coverage: {matched:,} / {MAX_NB_WORDS:,} vocabulary terms matched.\")\n"
]

# --- Step 7.1 & 8: Dual-Input Bi-LSTM Model Architecture & Tuning (Cell 22 & 24) ---
nb['cells'][22]['source'] = [
    "# --- Build Upgraded Dual-Input Bi-LSTM ---\n",
    "\n",
    "def build_dual_input_bilstm(learning_rate=1e-3):\n",
    "    # 1. Text Sequence Branch\n",
    "    text_input = Input(shape=(MAX_LEN,), name='text_input')\n",
    "    x = Embedding(\n",
    "        input_dim=MAX_NB_WORDS,\n",
    "        output_dim=100,\n",
    "        weights=[embedding_matrix],\n",
    "        input_length=MAX_LEN,\n",
    "        trainable=True\n",
    "    )(text_input)\n",
    "    x = SpatialDropout1D(0.3)(x)\n",
    "    \n",
    "    # Upgraded: Return sequences to execute dual pooling\n",
    "    x = Bidirectional(LSTM(64, return_sequences=True))(x)\n",
    "    \n",
    "    avg_pool = GlobalAveragePooling1D()(x)\n",
    "    max_pool = GlobalMaxPooling1D()(x)\n",
    "    conc_text = Concatenate()([avg_pool, max_pool])\n",
    "    \n",
    "    # 2. Metadata Branch\n",
    "    meta_input = Input(shape=(len(meta_cols),), name='meta_input')\n",
    "    \n",
    "    # 3. Concatenate and pass to Fully-Connected classifier\n",
    "    conc_all = Concatenate()([conc_text, meta_input])\n",
    "    \n",
    "    d = Dense(128, activation='relu')(conc_all)\n",
    "    d = Dropout(0.4)(d)\n",
    "    d = Dense(64, activation='relu')(d)\n",
    "    d = Dropout(0.3)(d)\n",
    "    outputs = Dense(3, activation='softmax')(d)\n",
    "    \n",
    "    model_func = Model(inputs=[text_input, meta_input], outputs=outputs)\n",
    "    model_func.compile(\n",
    "        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate, clipnorm=1.0),\n",
    "        loss='sparse_categorical_crossentropy',\n",
    "        metrics=['accuracy']\n",
    "    )\n",
    "    return model_func\n",
    "\n",
    "# Calculate class weights for deep training\n",
    "classes = np.unique(y_train)\n",
    "class_weights_arr = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)\n",
    "class_weights_dict = dict(zip(classes, class_weights_arr))\n",
    "\n",
    "# Run quick grid-search to find best learning rate\n",
    "best_lr = 0.001\n",
    "best_val_acc = 0\n",
    "\n",
    "for lr in [1e-3, 3e-4]:\n",
    "    print(f\"\\n--- Testing Bi-LSTM with Learning Rate: {lr} ---\")\n",
    "    temp_model = build_dual_input_bilstm(learning_rate=lr)\n",
    "    temp_hist = temp_model.fit(\n",
    "        [X_train_seq, X_train_meta], y_train,\n",
    "        epochs=3,\n",
    "        batch_size=64,\n",
    "        validation_data=([X_val_seq, X_val_meta], y_val),\n",
    "        class_weight=class_weights_dict,\n",
    "        verbose=1\n",
    "    )\n",
    "    val_acc = max(temp_hist.history['val_accuracy'])\n",
    "    if val_acc > best_val_acc:\n",
    "        best_val_acc = val_acc\n",
    "        best_lr = lr\n",
    "\n",
    "print(f\"\\nSuccess! Chosen Best Learning Rate: {best_lr} (Val Accuracy: {best_val_acc:.4f})\")\n"
]

nb['cells'][24]['source'] = [
    "# Train final optimized model for 8 epochs with early stopping\n",
    "final_model = build_dual_input_bilstm(learning_rate=best_lr)\n",
    "early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n",
    "\n",
    "history = final_model.fit(\n",
    "    [X_train_seq, X_train_meta], y_train,\n",
    "    epochs=10,\n",
    "    batch_size=64,\n",
    "    validation_data=([X_val_seq, X_val_meta], y_val),\n",
    "    class_weight=class_weights_dict,\n",
    "    callbacks=[early_stop],\n",
    "    verbose=1\n",
    ")\n"
]

# --- Step 9: Final Stress Evaluation (Cell 26) ---
nb['cells'][26]['source'] = [
    "# SVM Test Predictions\n",
    "svm_test_preds = svm_model.predict(X_test_svm)\n",
    "svm_test_acc = accuracy_score(y_test, svm_test_preds)\n",
    "\n",
    "# Bi-LSTM Test Predictions (Requires dual input list)\n",
    "lstm_test_probs = final_model.predict([X_test_seq, X_test_meta])\n",
    "lstm_test_preds = np.argmax(lstm_test_probs, axis=1)\n",
    "lstm_test_acc = accuracy_score(y_test, lstm_test_preds)\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(f\"Final SVM Test Accuracy: {svm_test_acc*100:.2f}%\")\n",
    "print(f\"Final Bi-LSTM Test Accuracy: {lstm_test_acc*100:.2f}%\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\"  OPTIMIZED BI-LSTM — Cross-Domain Test Report (Gmail + WhatsApp)\")\n",
    "print(\"=\"*50)\n",
    "print(classification_report(y_test, lstm_test_preds, target_names=label_mapping.keys()))\n"
]

# --- Step 10: Confusion Matrix (Cell 28) ---
nb['cells'][28]['source'] = [
    "cm = confusion_matrix(y_test, lstm_test_preds)\n",
    "plt.figure(figsize=(6, 5))\n",
    "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', \n",
    "            xticklabels=label_mapping.keys(), yticklabels=label_mapping.keys())\n",
    "plt.xlabel('Predicted Label')\n",
    "plt.ylabel('True Label')\n",
    "plt.title('Bi-LSTM Mistakes on Student Data')\n",
    "plt.show()\n"
]

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)
