import json
import os

notebook_path = 'notebooks/LARRY_NB_TextCNN.ipynb'

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# --- Step 1: Update Imports (Cell 2) ---
nb['cells'][2]['source'] = [
    "import os\n",
    "import re\n",
    "import string\n",
    "import zipfile\n",
    "import urllib.request\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing.text import Tokenizer\n",
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import (\n",
    "    Input, Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout,\n",
    "    Concatenate, SpatialDropout1D\n",
    ")\n",
    "\n",
    "# Fix random seeds so results are reproducible each run\n",
    "np.random.seed(42)\n",
    "tf.random.set_seed(42)\n",
    "\n",
    "# GloVe paths - check Kaggle input first to avoid download errors\n",
    "glove_kaggle_path = '/kaggle/input/glove6b100dtxt/glove.6B.100d.txt'\n",
    "glove_local_path = 'glove.6B.100d.txt'\n",
    "glove_url = \"https://nlp.stanford.edu/data/glove.6B.zip\"\n",
    "glove_zip = \"glove.6B.zip\"\n",
    "\n",
    "if os.path.exists(glove_kaggle_path):\n",
    "    print(\"Using Kaggle's GloVe dataset.\")\n",
    "    glove_path = glove_kaggle_path\n",
    "elif not os.path.exists(glove_local_path):\n",
    "    print(\"Downloading GloVe vectors from Stanford (this takes a few minutes)...\")\n",
    "    try:\n",
    "        opener = urllib.request.build_opener()\n",
    "        opener.addheaders = [('User-agent', 'Mozilla/5.0')]\n",
    "        urllib.request.install_opener(opener)\n",
    "        urllib.request.urlretrieve(glove_url, glove_zip)\n",
    "        print(\"Download done. Extracting...\")\n",
    "        with zipfile.ZipFile(glove_zip, 'r') as z:\n",
    "            z.extract(glove_local_path)\n",
    "        print(\"GloVe vectors ready.\")\n",
    "        glove_path = glove_local_path\n",
    "    except Exception as e:\n",
    "        print(f\"Download failed: {e}\")\n",
    "        print(\"PLEASE ENABLE INTERNET IN KAGGLE SETTINGS OR ADD GLOVE DATASET.\")\n",
    "        glove_path = None\n",
    "else:\n",
    "    print(\"GloVe vectors already available locally.\")\n",
    "    glove_path = glove_local_path\n",
    "\n",
    "# Load GloVe vectors into memory dictionary\n",
    "if glove_path:\n",
    "    print(\"Loading GloVe vectors into memory...\")\n",
    "    embeddings_lookup = {}\n",
    "    with open(glove_path, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            values = line.split()\n",
    "            word = values[0]\n",
    "            coefs = np.asarray(values[1:], dtype='float32')\n",
    "            embeddings_lookup[word] = coefs\n",
    "    print(f\"Loaded {len(embeddings_lookup):,} word vectors.\")"
]

# --- Step 4: Surgical Cleaning & Feature Extraction (Cell 10) ---
nb['cells'][10]['source'] = [
    "# --- Slang mapping including WhatsApp shortcuts ---\n",
    "slang_dictionary = {\n",
    "    r'\\bu\\b': 'you', r'\\bpls\\b': 'please', r'\\bplz\\b': 'please',\n",
    "    r'\\btmrw\\b': 'tomorrow', r'\\bwat\\b': 'what', r'\\bwud\\b': 'would',\n",
    "    r'\\bcuz\\b': 'because', r'\\bbtw\\b': 'by the way', r'\\bidk\\b': 'i do not know',\n",
    "    r'\\bomg\\b': 'oh my god', r'\\blol\\b': 'laughing', r'\\bthx\\b': 'thanks',\n",
    "    r'\\bsry\\b': 'sorry', r'\\bwanna\\b': 'want to', r'\\bgonna\\b': 'going to',\n",
    "    r'\\bur\\b': 'your', r'\\br\\b': 'are', r'\\bn\\b': 'and', r'\\bok\\b': 'okay'\n",
    "}\n",
    "\n",
    "def extract_meta_features(df):\n",
    "    \"\"\"\n",
    "    Extracts structural metadata indicators before cleaning strips punctuation/casing.\n",
    "    \"\"\"\n",
    "    # 1. Count of exclamations and question marks\n",
    "    df['exclamation_count'] = df['text'].apply(lambda x: str(x).count('!'))\n",
    "    df['question_count'] = df['text'].apply(lambda x: str(x).count('?'))\n",
    "    \n",
    "    # 2. Check for HTML fragments\n",
    "    df['has_html_artifacts'] = df['text'].apply(lambda x: 1 if re.search(r'<.*?>', str(x)) else 0)\n",
    "    \n",
    "    # 3. Check for shout capitalization (ALL CAPS)\n",
    "    df['is_all_caps'] = df['text'].apply(lambda x: 1 if str(x).isupper() and len(str(x)) > 5 else 0)\n",
    "    \n",
    "    # 4. Characters and words length\n",
    "    df['char_cnt'] = df['text'].apply(lambda x: len(str(x)))\n",
    "    df['word_cnt'] = df['text'].apply(lambda x: len(str(x).split()))\n",
    "    \n",
    "    # 5. Domain Shift Indicators (Technical platform names and billing alerts)\n",
    "    df['has_platform_mention'] = df['text'].apply(\n",
    "        lambda x: 1 if re.search(r'\\b(github|slack|coursera|udemy|paystack|railway|netlify|heroku)\\b', str(x).lower()) else 0\n",
    "    )\n",
    "    df['has_service_alert'] = df['text'].apply(\n",
    "        lambda x: 1 if re.search(r'\\b(invoice|billing|terminate|security|alert|reminder)\\b', str(x).lower()) else 0\n",
    "    )\n",
    "    return df\n",
    "\n",
    "def surgical_cleaner(text):\n",
    "    if type(text) != str: return \"\"\n",
    "    text = text.lower()\n",
    "    \n",
    "    # Remove HTML tags & URLs\n",
    "    text = re.sub(r'http\\S+|www\\.\\S+|@\\w+', '', text)\n",
    "    text = re.sub(r'<.*?>', '', text)\n",
    "    \n",
    "    # Strip common automated signatures\n",
    "    text = re.sub(r'sent from my (iphone|android|mobile)', '', text)\n",
    "    text = re.sub(r'please consider the environment before printing', '', text)\n",
    "    text = re.sub(r'--- forwarded message ---', '', text)\n",
    "    \n",
    "    # Standardize slang\n",
    "    for slang, correct in slang_dictionary.items():\n",
    "        text = re.sub(slang, correct, text)\n",
    "        \n",
    "    # Standardize contractions\n",
    "    text = re.sub(r\"can't\", \"cannot\", text)\n",
    "    text = re.sub(r\"don't\", \"do not\", text)\n",
    "    text = re.sub(r\"isn't\", \"is not\", text)\n",
    "    \n",
    "    # Strip punctuation\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    text = re.sub(r'\\s+', ' ', text).strip()\n",
    "    \n",
    "    return text if text else \"notification\"\n",
    "\n",
    "# --- Process Datasets ---\n",
    "print(\"Extracting structural metadata indicators...\")\n",
    "train_df = extract_meta_features(train_df)\n",
    "val_df   = extract_meta_features(val_df)\n",
    "test_df  = extract_meta_features(test_df)\n",
    "\n",
    "print(\"Applying surgical cleaner...\")\n",
    "train_df['clean'] = train_df['text'].apply(surgical_cleaner)\n",
    "val_df['clean']   = val_df['text'].apply(surgical_cleaner)\n",
    "test_df['clean']  = test_df['text'].apply(surgical_cleaner)\n",
    "\n",
    "print(\"Surgical cleaning complete!\")\n"
]

# --- Step 6: Upgraded Naive Bayes (Cell 15) ---
nb['cells'][15]['source'] = [
    "# --- Upgraded TF-IDF Vectorizer with Sublinear TF Scaling ---\n",
    "print(\"Fitting TF-IDF Vectorizer...\")\n",
    "tfidf_vec = TfidfVectorizer(\n",
    "    max_features=15000, \n",
    "    ngram_range=(1, 3), \n",
    "    sublinear_tf=True,  # Logarithmic scaling: 1 + log(tf)\n",
    "    min_df=2            # Drops noise tokens occurring only once\n",
    ")\n",
    "\n",
    "X_train_tfidf = tfidf_vec.fit_transform(train_df['clean'])\n",
    "X_val_tfidf   = tfidf_vec.transform(val_df['clean'])\n",
    "X_test_tfidf  = tfidf_vec.transform(test_df['clean'])\n",
    "\n",
    "print(f\"Naive Bayes features shape: {X_train_tfidf.shape}\")\n"
]

# --- Step 7: Preparing Sequence & GloVe Matrix & Build (Cell 19) ---
nb['cells'][19]['source'] = [
    "MAX_WORDS = 25000\n",
    "MAX_LEN = 200\n",
    "\n",
    "# 1. Tokenizing Clean Text\n",
    "cnn_tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token='<OOV>')\n",
    "cnn_tokenizer.fit_on_texts(train_df['clean'])\n",
    "\n",
    "X_train_seq = pad_sequences(cnn_tokenizer.texts_to_sequences(train_df['clean']), maxlen=MAX_LEN)\n",
    "X_val_seq   = pad_sequences(cnn_tokenizer.texts_to_sequences(val_df['clean']),   maxlen=MAX_LEN)\n",
    "X_test_seq  = pad_sequences(cnn_tokenizer.texts_to_sequences(test_df['clean']),  maxlen=MAX_LEN)\n",
    "\n",
    "# 2. Scale Structural Metadata features\n",
    "meta_cols = ['exclamation_count', 'question_count', 'has_html_artifacts',\n",
    "             'is_all_caps', 'char_cnt', 'word_cnt',\n",
    "             'has_platform_mention', 'has_service_alert']\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_meta = scaler.fit_transform(train_df[meta_cols].values)\n",
    "X_val_meta   = scaler.transform(val_df[meta_cols].values)\n",
    "X_test_meta  = scaler.transform(test_df[meta_cols].values)\n",
    "\n",
    "# 3. Build GloVe Embedding Matrix\n",
    "embedding_matrix = np.zeros((MAX_WORDS, 100))\n",
    "matched = 0\n",
    "for word, idx in cnn_tokenizer.word_index.items():\n",
    "    if idx < MAX_WORDS:\n",
    "        vec = embeddings_lookup.get(word)\n",
    "        if vec is not None:\n",
    "            embedding_matrix[idx] = vec\n",
    "            matched += 1\n",
    "\n",
    "print(f\"GloVe Coverage for TextCNN: {matched:,} / {MAX_WORDS:,} vocabulary terms matched.\")\n",
    "\n",
    "# --- Build Upgraded Dual-Input TextCNN ---\n",
    "\n",
    "def build_larry_cnn(learning_rate=1e-3):\n",
    "    # 1. Text Sequence Branch\n",
    "    input_layer = Input(shape=(MAX_LEN,), name='text_input')\n",
    "    embedding = Embedding(\n",
    "        input_dim=MAX_WORDS,\n",
    "        output_dim=100,\n",
    "        weights=[embedding_matrix],\n",
    "        input_length=MAX_LEN,\n",
    "        trainable=True\n",
    "    )(input_layer)\n",
    "    s_dropout = SpatialDropout1D(0.3)(embedding)\n",
    "    \n",
    "    # Powerful Multi-Filter Convolutional channels\n",
    "    convs = []\n",
    "    for fsize in [3, 5, 7, 9]:\n",
    "        conv = Conv1D(128, fsize, activation='relu')(s_dropout)\n",
    "        pool = GlobalMaxPooling1D()(conv)\n",
    "        convs.append(pool)\n",
    "    \n",
    "    merged_conv = Concatenate()(convs)\n",
    "    \n",
    "    # 2. Metadata Branch\n",
    "    meta_input = Input(shape=(len(meta_cols),), name='meta_input')\n",
    "    \n",
    "    # 3. Concatenate CNN + Metadata\n",
    "    merged_all = Concatenate()([merged_conv, meta_input])\n",
    "    \n",
    "    drop = Dropout(0.5)(merged_all)\n",
    "    dense = Dense(128, activation='relu')(drop)\n",
    "    output = Dense(3, activation='softmax')(dense)\n",
    "    \n",
    "    model_func = Model(inputs=[input_layer, meta_input], outputs=output)\n",
    "    model_func.compile(\n",
    "        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),\n",
    "        loss='sparse_categorical_crossentropy',\n",
    "        metrics=['accuracy']\n",
    "    )\n",
    "    return model_func\n",
    "\n",
    "larry_cnn = build_larry_cnn()\n",
    "print(larry_cnn.summary())\n"
]

# --- Step 7.1: Tuning (Cell 21) ---
nb['cells'][21]['source'] = [
    "# Calculate class weights for training\n",
    "classes = np.unique(y_train)\n",
    "class_weights_arr = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)\n",
    "class_weights_dict = dict(zip(classes, class_weights_arr))\n",
    "\n",
    "# Run quick grid-search to find best learning rate\n",
    "best_lr_cnn = 0.001\n",
    "best_val_acc_cnn = 0\n",
    "\n",
    "for lr in [1e-3, 5e-4]:\n",
    "    print(f\"\\n--- Testing TextCNN with Learning Rate: {lr} ---\")\n",
    "    temp_cnn = build_larry_cnn(learning_rate=lr)\n",
    "    temp_hist = temp_cnn.fit(\n",
    "        [X_train_seq, X_train_meta], y_train,\n",
    "        epochs=3,\n",
    "        batch_size=64,\n",
    "        validation_data=([X_val_seq, X_val_meta], y_val),\n",
    "        class_weight=class_weights_dict,\n",
    "        verbose=1\n",
    "    )\n",
    "    val_acc = max(temp_hist.history['val_accuracy'])\n",
    "    if val_acc > best_val_acc_cnn:\n",
    "        best_val_acc_cnn = val_acc\n",
    "        best_lr_cnn = lr\n",
    "\n",
    "print(f\"\\nSuccess! Chosen Best Learning Rate: {best_lr_cnn} (Val Accuracy: {best_val_acc_cnn:.4f})\")\n"
]

# --- Step 8: Final Training (Cell 23) ---
nb['cells'][23]['source'] = [
    "# Train final optimized model for 12 epochs with early stopping\n",
    "larry_cnn = build_larry_cnn(learning_rate=best_lr_cnn)\n",
    "early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n",
    "\n",
    "history = larry_cnn.fit(\n",
    "    [X_train_seq, X_train_meta], y_train,\n",
    "    epochs=12,\n",
    "    batch_size=64,\n",
    "    validation_data=([X_val_seq, X_val_meta], y_val),\n",
    "    class_weight=class_weights_dict,\n",
    "    callbacks=[early_stop],\n",
    "    verbose=1\n",
    ")\n"
]

# --- Step 9: Testing (Cell 25) ---
nb['cells'][25]['source'] = [
    "# Naive Bayes Test Performance\n",
    "test_pred_nb = nb_clf.predict(X_test_tfidf)\n",
    "nb_acc = accuracy_score(y_test, test_pred_nb)\n",
    "\n",
    "# TextCNN Test Performance (Requires dual inputs)\n",
    "test_pred_cnn_probs = larry_cnn.predict([X_test_seq, X_test_meta])\n",
    "test_pred_cnn = np.argmax(test_pred_cnn_probs, axis=1)\n",
    "cnn_acc = accuracy_score(y_test, test_pred_cnn)\n",
    "\n",
    "print(f\"Upgraded Naive Bayes Test Accuracy: {nb_acc*100:.2f}%\")\n",
    "print(f\"Upgraded TextCNN Test Accuracy: {cnn_acc*100:.2f}%\")\n",
    "\n",
    "# Visual Comparison\n",
    "plt.figure(figsize=(8, 5))\n",
    "results = pd.DataFrame({\n",
    "    'Model': ['Naive Bayes', 'TextCNN'],\n",
    "    'Accuracy': [nb_acc, cnn_acc]\n",
    "})\n",
    "sns.barplot(x='Model', y='Accuracy', data=results, palette='coolwarm', hue='Model', legend=False)\n",
    "plt.axhline(0.8, color='red', linestyle='--', label='80% Goal')\n",
    "plt.title('Final Results on Student Communication Data')\n",
    "plt.ylim(0, 1)\n",
    "plt.legend()\n",
    "plt.show()\n"
]

# --- Step 10: Ensemble (Cell 27) ---
nb['cells'][27]['source'] = [
    "# 1. Get probabilities from both models\n",
    "nb_probs = nb_clf.predict_proba(X_test_tfidf)\n",
    "cnn_probs = larry_cnn.predict([X_test_seq, X_test_meta])  # Updated to dual inputs\n",
    "\n",
    "# 2. Average the probabilities (Soft Voting)\n",
    "ensemble_probs = (nb_probs + cnn_probs) / 2\n",
    "ensemble_preds = np.argmax(ensemble_probs, axis=1)\n",
    "\n",
    "ensemble_acc = accuracy_score(y_test, ensemble_preds)\n",
    "print(f\"Joint Soft-Voting Ensemble Test Accuracy: {ensemble_acc*100:.2f}%\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\"  OPTIMIZED ENSEMBLE — Cross-Domain Test Report (Gmail + WhatsApp)\")\n",
    "print(\"=\"*50)\n",
    "print(classification_report(y_test, ensemble_preds, target_names=label_mapping.keys()))\n",
    "\n",
    "# 3. Final Comparison Visualization\n",
    "plt.figure(figsize=(10, 6))\n",
    "models_list = ['Naive Bayes', 'TextCNN', 'Ensemble']\n",
    "accuracies_list = [nb_acc, cnn_acc, ensemble_acc]\n",
    "\n",
    "sns.barplot(x=models_list, y=accuracies_list, palette='viridis')\n",
    "plt.axhline(0.8, color='red', linestyle='--', label='80% Target')\n",
    "plt.title('Final Model Performance Comparison')\n",
    "plt.ylabel('Accuracy')\n",
    "plt.ylim(0, 1)\n",
    "plt.legend()\n",
    "plt.show()\n"
]

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)
