import json
import os

notebook_path = 'notebooks/gru_random_forest_improved.ipynb'

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# --- Step 1: Update Imports (Cell 1) ---
nb['cells'][1]['source'] = [
    "import os\n",
    "import re\n",
    "import zipfile\n",
    "import urllib.request\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import classification_report, accuracy_score, confusion_matrix\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing.text import Tokenizer\n",
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import (\n",
    "    Embedding, GRU, Dense, Dropout, SpatialDropout1D, Bidirectional,\n",
    "    Input, Concatenate, GlobalAveragePooling1D, GlobalMaxPooling1D, \n",
    "    Layer, LayerNormalization\n",
    ")\n",
    "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau\n",
    "\n",
    "# --- Added for Random Forest Lexicon Features ---\n",
    "import nltk\n",
    "from nltk.sentiment.vader import SentimentIntensityAnalyzer\n",
    "try:\n",
    "    nltk.data.find('sentiment/vader_lexicon.zip')\n",
    "except LookupError:\n",
    "    nltk.download('vader_lexicon')\n",
    "\n",
    "# Fix random seeds so results are reproducible each run\n",
    "np.random.seed(42)\n",
    "tf.random.set_seed(42)\n",
    "\n",
    "# GloVe paths - check Kaggle input first to avoid download errors\n",
    "glove_kaggle_path = '/kaggle/input/glove6b100dtxt/glove.6B.100d.txt'\n",
    "glove_local_path = 'glove.6B.100d.txt'\n",
    "glove_url = \"https://nlp.stanford.edu/data/glove.6B.zip\"\n",
    "glove_zip = \"glove.6B.zip\"\n",
    "\n",
    "if os.path.exists(glove_kaggle_path):\n",
    "    print(\"Using Kaggle GloVe path.\")\n",
    "    glove_path = glove_kaggle_path\n",
    "elif not os.path.exists(glove_local_path):\n",
    "    print(\"Downloading GloVe vectors...\")\n",
    "    opener = urllib.request.build_opener()\n",
    "    opener.addheaders = [('User-agent', 'Mozilla/5.0')]\n",
    "    urllib.request.install_opener(opener)\n",
    "    urllib.request.urlretrieve(glove_url, glove_zip)\n",
    "    with zipfile.ZipFile(glove_zip, 'r') as z:\n",
    "        z.extract(glove_local_path)\n",
    "    glove_path = glove_local_path\n",
    "else:\n",
    "    glove_path = glove_local_path\n"
]

# --- Step 5: High-Density Feature Stack for Random Forest (Cell 11) ---
nb['cells'][11]['source'] = [
    "# --- TF-IDF Weighted GloVe Pooling ---\n",
    "def compute_tfidf_weighted_glove(texts, tfidf_vec, glove_dict, dim=100):\n",
    "    tfidf_matrix = tfidf_vec.transform(texts).toarray()\n",
    "    feature_names = tfidf_vec.get_feature_names_out()\n",
    "    word2idx = {word: idx for idx, word in enumerate(feature_names)}\n",
    "    \n",
    "    vecs = []\n",
    "    for i, text in enumerate(texts):\n",
    "        tokens = text.split()\n",
    "        token_vecs = []\n",
    "        weights = []\n",
    "        for w in tokens:\n",
    "            if w in glove_dict:\n",
    "                token_vecs.append(glove_dict[w])\n",
    "                if w in word2idx:\n",
    "                    weights.append(tfidf_matrix[i, word2idx[w]])\n",
    "                else:\n",
    "                    weights.append(1e-3)\n",
    "        if token_vecs:\n",
    "            token_vecs = np.array(token_vecs)\n",
    "            weights = np.array(weights)\n",
    "            weight_sum = np.sum(weights)\n",
    "            if weight_sum > 0:\n",
    "                weights = weights / weight_sum\n",
    "                weighted_vec = np.sum(token_vecs * weights[:, np.newaxis], axis=0)\n",
    "            else:\n",
    "                weighted_vec = np.mean(token_vecs, axis=0)\n",
    "            vecs.append(weighted_vec)\n",
    "        else:\n",
    "            vecs.append(np.zeros(dim))\n",
    "    return np.array(vecs)\n",
    "\n",
    "# --- VADER Sentiment Feature Extraction ---\n",
    "print(\"Extracting VADER lexicon sentiment scores...\")\n",
    "sia = SentimentIntensityAnalyzer()\n",
    "def extract_vader_features(texts):\n",
    "    vader_feats = []\n",
    "    for text in texts:\n",
    "        scores = sia.polarity_scores(str(text))\n",
    "        vader_feats.append([scores['neg'], scores['neu'], scores['pos'], scores['compound']])\n",
    "    return np.array(vader_feats)\n",
    "\n",
    "# 1. Fit TF-IDF on cleaned training text (top 500 features)\n",
    "print(\"Fitting TF-IDF vectorizer...\")\n",
    "tfidf_rf = TfidfVectorizer(max_features=500, ngram_range=(1, 2), sublinear_tf=True, min_df=2)\n",
    "tfidf_rf.fit(train_df['cleaned_text'])\n",
    "\n",
    "# 2. Build TF-IDF Weighted GloVe vectors\n",
    "print(\"Building TF-IDF Weighted GloVe vectors...\")\n",
    "X_train_glove = compute_tfidf_weighted_glove(train_df['cleaned_text'], tfidf_rf, embeddings_lookup)\n",
    "X_val_glove   = compute_tfidf_weighted_glove(val_df['cleaned_text'],   tfidf_rf, embeddings_lookup)\n",
    "X_test_glove  = compute_tfidf_weighted_glove(test_df['cleaned_text'],  tfidf_rf, embeddings_lookup)\n",
    "\n",
    "# 3. Extract VADER features from RAW text\n",
    "vader_train = extract_vader_features(train_df['text'])\n",
    "vader_val   = extract_vader_features(val_df['text'])\n",
    "vader_test  = extract_vader_features(test_df['text'])\n",
    "\n",
    "# 4. Define all structural metadata features\n",
    "meta_cols = ['exclamation_count', 'question_count', 'has_html_artifacts',\n",
    "             'is_all_caps', 'char_cnt', 'word_cnt',\n",
    "             'has_platform_mention', 'has_service_alert']\n",
    "\n",
    "# 5. Fit Sparse TF-IDF for direct feature injection\n",
    "X_train_tfidf = tfidf_rf.transform(train_df['cleaned_text']).toarray()\n",
    "X_val_tfidf   = tfidf_rf.transform(val_df['cleaned_text']).toarray()\n",
    "X_test_tfidf  = tfidf_rf.transform(test_df['cleaned_text']).toarray()\n",
    "\n",
    "# 6. Stack into a single dense representational space (Corrected concatenation)\n",
    "X_train_rf = np.hstack([X_train_glove, vader_train, X_train_tfidf, train_df[meta_cols].values])\n",
    "X_val_rf   = np.hstack([X_val_glove,   vader_val,   X_val_tfidf,   val_df[meta_cols].values])\n",
    "X_test_rf  = np.hstack([X_test_glove,  vader_test,  X_test_tfidf,  test_df[meta_cols].values])\n",
    "\n",
    "print(f\"Corrected RF feature matrix shape — Train: {X_train_rf.shape}, Test: {X_test_rf.shape}\")\n"
]

# --- Step 7: Multi-Input GRU Model Build with Attention (Cell 16) ---
nb['cells'][16]['source'] = [
    "# --- Custom Attention Layer ---\n",
    "class Attention(Layer):\n",
    "    def __init__(self, **kwargs):\n",
    "        super(Attention, self).__init__(**kwargs)\n",
    "    \n",
    "    def build(self, input_shape):\n",
    "        self.W = self.add_weight(name='attention_weight', shape=(input_shape[-1], 1), initializer='random_normal', trainable=True)\n",
    "        self.b = self.add_weight(name='attention_bias', shape=(input_shape[1], 1), initializer='zeros', trainable=True)\n",
    "        super(Attention, self).build(input_shape)\n",
    "\n",
    "    def call(self, x):\n",
    "        e = tf.nn.tanh(tf.matmul(x, self.W) + self.b)\n",
    "        a = tf.nn.softmax(e, axis=1)\n",
    "        output = x * a\n",
    "        return tf.reduce_sum(output, axis=1)\n",
    "\n",
    "# --- Advanced Multi-Input GRU with Attention ---\n",
    "text_input = Input(shape=(MAX_LEN,), name='text_input')\n",
    "x = Embedding(\n",
    "    input_dim=VOCAB_SIZE,\n",
    "    output_dim=100,\n",
    "    weights=[embedding_matrix],\n",
    "    input_length=MAX_LEN,\n",
    "    trainable=True\n",
    ")(text_input)\n",
    "x = SpatialDropout1D(0.4)(x)\n",
    "\n",
    "x = Bidirectional(GRU(128, return_sequences=True, dropout=0.3, recurrent_dropout=0.0))(x)\n",
    "x = LayerNormalization()(x)\n",
    "x = Bidirectional(GRU(64, return_sequences=True, dropout=0.3, recurrent_dropout=0.0))(x)\n",
    "x = LayerNormalization()(x)\n",
    "\n",
    "avg_pool = GlobalAveragePooling1D()(x)\n",
    "max_pool = GlobalMaxPooling1D()(x)\n",
    "att_pool = Attention()(x)\n",
    "\n",
    "conc_text = Concatenate()([avg_pool, max_pool, att_pool])\n",
    "\n",
    "meta_input = Input(shape=(len(meta_cols),), name='meta_input')\n",
    "conc_all = Concatenate()([conc_text, meta_input])\n",
    "\n",
    "d = Dense(256, activation='relu')(conc_all)\n",
    "d = Dropout(0.5)(d)\n",
    "d = Dense(128, activation='relu')(d)\n",
    "d = Dropout(0.4)(d)\n",
    "outputs = Dense(3, activation='softmax')(d)\n",
    "\n",
    "gru_model = Model(inputs=[text_input, meta_input], outputs=outputs)\n",
    "gru_model.compile(\n",
    "    loss='sparse_categorical_crossentropy',\n",
    "    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-4, clipnorm=1.0),\n",
    "    metrics=['accuracy']\n",
    ")\n",
    "gru_model.summary()\n"
]

# --- Step 7: Training the GRU Model (Cell 17) ---
nb['cells'][17]['source'] = [
    "# --- Training with improved configuration ---\n",
    "classes = np.unique(y_train_gru)\n",
    "class_weights_arr = compute_class_weight(class_weight='balanced', classes=classes, y=y_train_gru)\n",
    "class_weights = dict(zip(classes, class_weights_arr))\n",
    "\n",
    "early_stop = EarlyStopping(monitor='val_loss', patience=4, restore_best_weights=True)\n",
    "reduce_lr  = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6)\n",
    "\n",
    "print(\"Training Advanced GRU with Attention...\")\n",
    "history = gru_model.fit(\n",
    "    [X_train_gru, X_train_meta], y_train_gru,\n",
    "    epochs=20,\n",
    "    batch_size=32,\n",
    "    validation_data=([X_val_gru, X_val_meta], y_val_gru),\n",
    "    class_weight=class_weights,\n",
    "    callbacks=[early_stop, reduce_lr],\n",
    "    verbose=1\n",
    ")\n"
]

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)
